Main svc
EndorpfinSplash/java-explore-with-me pull request #8
Opened 2024-08-19 21:06 UTC by EndorpfinSplash

Please check my work

2024-08-21 12:07 UTC, YazykovMikhail requested changes
Обрати внимание, местами есть код, который закомментирован, если это задел на будещее или какие кто комментарии - ок. 
Но если это уже не актуально, стоит сразу удалять

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/event/EventControllerAdmin.java
> +public class EventControllerAdmin {
Молодец что разделил на разные эндпоинты Admin/Private/Public

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/event/EventControllerAdmin.java
> +        log.info("GET request to fetch list of events received.");
А как потом узнать что пришло?
Логирвоание нужно для отладки/поиска проблем. Если нет информации ничего не будет понятно. 

Аналогично у тебя нигде нет лога с вответом, как потом узнать что было в ответе

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/event/EventControllerAdmin.java
> +        log.info("PATCH request to update eventId={} received.", eventId);
То что id залогировал хорошо, но как же сам запрос? Человек скажет я положил 1000000 миллион на счет, а в итоге пришло 1000, а проверить никак нельзя будет что было насамом деле.
Входящие/исходящие даные стоит логировать - это необходимый минимум

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/event/EventControllerAdmin.java
> +package ru.practicum.ewm.event;
Очень много классов в одном пакете, сделай более структурно.
Например введи еще папки
model
service
enum
reposytory
mapper

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/event/StateAction.java
> +//package ru.practicum.ewm.event;
Получается не нужно?
Удаляй рсазу

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/exception/ApiError.java
> +package ru.practicum.ewm.exception;
Напишу комментарий тут, исключений прям много, обрати внимание что есть те которые не используются - удаля сразу.

Не на каждый случай нужно свое исключение, иногда лучше обьеденять в подгруппы, например
BusinessServiceException - и тут будут все исключения связанные с бизнес процессами
EntityNotFound - обьект не найдет - а какой уже обьект, это убдет внутри самого исключения

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/request/RequestService.java
> +        User requester = userRepository.findById(userId).orElseThrow(
Много где у тебя таких проверок в методах и как ты видешь они занимают много места. 
Можно сделать  два варианта:
1) Вызывать не из репозитория запрос, а из сервиса
    public UserDto getUserById(Long userId) {
Ведь в этом метоже уже есть проверка. 
2) Выеси все проверки в один приватный метод. что бы это была одна строчка кода в этом методе и не мешала бизнес процессам, а кто хочет может спуститься и посомтреть что там за проверки делаются. 
Но лучше конечно использовать первый вариант где это вохможно, стоит ищбешать дублирвоания кода

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/request/RequestService.java
> +        User requester = userRepository.findById(userId).orElseThrow(
Комментарий касается всего кода

2024-08-21 12:07 UTC, YazykovMikhail commented on explore-with-me-service/src/main/java/ru/practicum/ewm/user/dto/NewUserRequest.java
> +public class NewUserRequest {
Сращайся придерживаться одного шаблона в названиях всего, в том числе dto, именно это хороший пример, но в других местах у тебя есть приставка dto 

Есть множество вариантов градации. Например как у тебя тут
 NewUserRequest
 NewUserResponse - т.е для каждого эндпоинта будет свой запрос и ответ. Если видишь что во всемм контроллере ответы имеют один формат, то dto для ответа можно обобщить, например:
 UserResponse - сразу понятно чтоэто ответ дляэндпоинтов User. 
 Приставка dto - не обязательна и так понятно будет что это dto

2024-08-21 21:43 UTC, EndorpfinSplash commented on explore-with-me-service/src/main/java/ru/practicum/ewm/user/dto/NewUserRequest.java
> +public class NewUserRequest {
В данном случае придерживался рекомендаций наставника  - называть классы так же и как в спецификации к заданию 
https://raw.githubusercontent.com/yandex-praktikum/java-explore-with-me/main/ewm-main-service-spec.json

2024-08-22 06:44 UTC, YazykovMikhail approved these changes

2024-08-22 08:11 UTC, merged